service: werdino-daily-lambda
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
functions:
  runWerdino:
    handler: handler.runWerdino
    environment:
      SLACK_WEBHOOK_ADDRESS: ${file(./config/config.${self:provider.stage, }.json):SLACK_WEBHOOK_ADDRESS}
      SLACK_WEBHOOK_ADDRESS2: ${file(./config/config.${self:provider.stage, }.json):SLACK_WEBHOOK_ADDRESS2}
      SLACK_WEBHOOK_ADDRESS3: ${file(./config/config.${self:provider.stage, }.json):SLACK_WEBHOOK_ADDRESS3}
      GOOGLE_APPLICATION_CREDENTIALS: ${file(./config/config.${self:provider.stage, }.json):GOOGLE_APPLICATION_CREDENTIALS}
    events:
    - schedule:
        rate: cron(0 5 ? * MON-FRI *)
        enabled: true