service: tx-chef-lambda
provider:
  name: aws
  profile: tamedia
  region: us-east-2
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  role: arn:aws:iam::716110578696:role/service-role/info-werdino-lambda-role-gfqzye3q
functions:
  runWerdino:
    handler: handler.runWerdino
    environment:
      WERDINO_WEBHOOK_ADDRESSES: ${file(./config/config.${self:provider.stage, }.json):WERDINO_WEBHOOK_ADDRESSES}
      BUBENBERG_WEBHOOK_ADDRESSES: ${file(./config/config.${self:provider.stage, }.json):BUBENBERG_WEBHOOK_ADDRESSES}
      GOOGLE_APPLICATION_CREDENTIALS: ${file(./config/config.${self:provider.stage, }.json):GOOGLE_APPLICATION_CREDENTIALS}
    events:
    - schedule:
        rate: cron(0 5 ? * MON-FRI *)
        enabled: true