service: werdino-daily-lambda
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
functions:
  runWerdino:
    handler: handler.runWerdino
    environment:
      WERDINO_WEBHOOK_ADDRESSES: ${file(./config/config.${self:provider.stage, }.json):WERDINO_WEBHOOK_ADDRESSES}
      GOOGLE_APPLICATION_CREDENTIALS: ${file(./config/config.${self:provider.stage, }.json):GOOGLE_APPLICATION_CREDENTIALS}
    events:
    - schedule:
        rate: cron(0 5 ? * MON-FRI *)
        enabled: true